<html>
  <head>
    <style>
       /* Set the size of the div element that contains the map */
      #map {
        height: 600px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
    </style>
  </head>
  <body>
    
    <!--The div element for the map -->
    <div id="map">
    <script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  var uluru = {lat: 45.559051, lng: 18.682488 };
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 12, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCFP6Q3eGRZvrDe28CJVmr3oJrWsNSmw_Q&callback=initMap">
    </script>
    </div>
    <div>
    <h4>
    Stjepana Radića 12
    <br>
    31000 Osijek
    <br>
    Radno vrijeme:
    <br>
    07-23h
    </div>
  </body>
</html>