<fieldset class="fieldset">
    <legend>Popunite tražene podatke</legend>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'naziv','Naziv');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'opis','Opis');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'kolicina','Količina (dcl)');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'osoba','Osoba');?>



</fieldset>
<hr />