<fieldset class="fieldset">
    <legend>Izradi novu objavu!</legend>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'naslov','Naslov');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'sadrzaj','Sadržaj');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'datum_objave','Datum Objave');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'osoba','Osoba');?>


</fieldset>
<hr />